using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;

namespace GenericPipelines.CodeGeneration;

internal static class FileGenerator
{
    public static string GenerateFile(Action<IndentedTextWriter> generateCode)
    {
        StringBuilder builder = new(2000);
        GenerateCode(builder, generateCode);
        return builder.ToString();
    }

    private static void GenerateCode(StringBuilder builder, Action<IndentedTextWriter> generateCode)
    {
        using StringWriter writer = new StringWriter(builder, CultureInfo.InvariantCulture);
        using IndentedTextWriter source = new IndentedTextWriter(writer, "    ");

        GenerateHeader(source);
        generateCode(source);
    }
    
    private static void GenerateHeader(IndentedTextWriter source)
    {
        source.WriteLine("// <auto-generated/>");
        source.WriteLine();
        source.WriteLine("#pragma warning disable");
        source.WriteLine("#nullable enable");
        source.WriteLine();
    }
}